### ISSUE TITLE
askcreds - fails to compile

### ISSUE THREAD

**Issue by jabra-** [outflanknl/C2-Tool-Collection#1]
```
Askcreds.c: In function ‘AskCreds’:
Askcreds.c:111:9: error: ‘CREDUIWIN_GENERIC’ undeclared (first use in this function); did you mean ‘CRED_TYPE_GENERIC’?
         CREDUIWIN_GENERIC | CREDUIWIN_CHECKBOX
         ^~~~~~~~~~~~~~~~~
         CRED_TYPE_GENERIC
Askcreds.c:111:9: note: each undeclared identifier is reported only once for each function it appears in
Askcreds.c:111:29: error: ‘CREDUIWIN_CHECKBOX’ undeclared (first use in this function); did you mean ‘CREDUI_INFO’?
         CREDUIWIN_GENERIC | CREDUIWIN_CHECKBOX
                             ^~~~~~~~~~~~~~~~~~
                             CREDUI_INFO
```

**Comment by Cn33liz** [comment]
How do you compile? Tools should compile successfully on latest version of Kali/Mac OSX with latest version of Mingw-w64 compiler.

**Comment by jabra-** [comment]
OS: debian buster.
used `make` to compile.
All of the other BOFs compiled just fine.

**Comment by jabra-** [comment]
```
+#define CREDUIWIN_GENERIC 0x1
+#define CREDUIWIN_CHECKBOX 0x2
```

fixes it.
ref: https://github.com/kinke/mingw-w64-crt/blob/master/mingw-w64-headers/include/wincred.h#L327

**Comment by fastlorenzo** [comment]
Same issue here with Ubuntu 20.04.3 LTS

**Comment by Cn33liz** [comment]
Tools have been tested (and compiled) successfully on Kali (latest) and mac OSX with Mingw-w64 installed (see support note in readme). I hope the above #define change fixes the issue on Debian/Ubuntu otherwise I recommend compiling the tools on a Kali VM.

**Comment by fastlorenzo** [comment]
@Cn33liz indeed, the target is to build on Kali but I was using Ubuntu 20.04 for dev and noticed the issue. I thought it would be interesting to add a reference here if others have the same issue 😉 
The #define change fixes the issue

**Comment by Cn33liz** [comment]
Good point, i'll add this to the readme, thank you :)

**Comment by Cn33liz** [comment]
Added the proposed solution to an issue section within the readme file. If this is okay with you both then i'll close the issue?

**Comment by jabra-** [comment]
Why not just add these to your .h header?

Here is a reference from microsoft:
https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-creduipromptforwindowscredentialsa

**Comment by fastlorenzo** [comment]
FYI I've tried with Kali 2022.1 from a few months old (missing lot of updates) and it was giving the same error as above.
After upgrading the system, the error was no longer showing up.

**Comment by Cn33liz** [comment]
I added the #defines to the header file. Can you verify if everything is working as expected now?

**Comment by fastlorenzo** [comment]
Looks like it's working now, on Ubuntu 20.04 as well, thanks! 😄

**Comment by jabra-** [comment]
great! compiles perfectly now. good to close.

**Comment by Cn33liz** [comment]
Great thanks for the feedback!
